const express=require('express')
const router=express.Router()
const { registerController, loginController } = require('./auth.controller')
const protect=require('../../middleware/auth.middleware')
const authorizeRole = require('../../middleware/role.middleware')
const { validate } = require('../../middleware/validate.middleware')
const { registerSchema, loginSchema } = require('./auth.validation')
router.post('/register',protect,authorizeRole('admin','super_admin'),validate(registerSchema),registerController)
router.post('/login',validate(loginSchema),loginController)
module.exports=router
